### ISSUE TITLE
Player scrolls page a second after pausing the video

### ISSUE THREAD

**Issue by Martin-Pitt** [moay/afterglow#35] opened 2017-02-08 11:23 UTC
Scenario:
User pauses video and starts scrolling page.

Within seconds the entire page scroll backs to the top of the video.

User is really annoyed that the whole page scrolled for no reason, back to content they seen already and were trying to ignore.

They leave the website.

Example:
https://youtu.be/NQYjaC0NeFY

---

Can this issue be fixed please?
It happens on the main afterglow website as well, on all major browsers we tested with.

It's a really nice video player, but this weird bug causing the entire page to jank after pausing the video is disconcerting to the users' experience.

**Comment by moay** [comment] 2017-02-08 11:28
Hi there!

Just tested that out. Played the video on the afterglow website, then paused it and immediately scrolled down. No strange behaviour, no scrolling back. Tested on chrome and firefox and on several websites.  

Do you have a video or could you screencast the behaviour? We are not able to reproduce this bug.

**Comment by moay** [comment] 2017-02-08 11:30
Sorry, just saw the screencast. I'll look into it.

**Comment by moay** [comment] 2017-02-08 11:32
Seems to happen only when explicitly using the pause button (not pausing when clicking elsewhere on the player). Can you confirm that, @Martin-Pitt?

**Comment by Martin-Pitt** [comment] 2017-02-08 11:38
@moay  Yep, doesn't trigger on ending of video or when clicking the video itself. Seems only via the pause button in the player bar.

**Comment by moay** [comment] 2017-02-08 12:32
Fixed with the latest commits, new release 0.4.1 is available and will be pushed to the CDN within a few hours.

**Closed by moay** 2017-02-08 12:32 UTC
Labels: bug
