### ISSUE TITLE
function deprecated

### ISSUE THREAD

**Issue by vinisouza** [moay/afterglow#18] opened 2015-11-17 15:48 UTC
my console output this message.

VIDEOJS: WARN: Access to videojs.players is deprecated; use videojs.getPlayers instead

maybe would better update the core.

Thanks. Excellent player

**Comment by moay** [comment] 2015-11-17 16:09
Hi @vinisouza :) Yep, that is planned for the next version. Thanks for the heads up!

**Comment by moay** [comment] 2015-11-17 16:13
@vinisouza What browser do you use? What version of afterglow are you using? Doesn't happen on Chrome actually... Any link where I can see this happen?

**Comment by vinisouza** [comment] 2015-11-17 19:12
Firefox 42.0; Afterglow 0.3.0;
![captura de tela de 2015-11-17 16 09 16](https://cloud.githubusercontent.com/assets/828731/11221778/a6c92dee-8d45-11e5-8a62-d82f7f721ecd.png)

Happens when the play is triggered. The video works, but emit this alert

**Comment by moay** [comment] 2016-02-09 09:51
Sorry, still can't reproduce this error. Do you have a link where I can see that happen?

**Comment by moay** [comment] 2016-02-09 14:43
Should be fixed with the next release.

**Closed by moay** 2016-02-09 14:43 UTC
